//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace ASE_Project.order_details {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="orderSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class order : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback order_enterOperationCompleted;
        
        private System.Threading.SendOrPostCallback address_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback ven_orderOperationCompleted;
        
        private System.Threading.SendOrPostCallback usr_orderOperationCompleted;
        
        private System.Threading.SendOrPostCallback order_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback chart_venOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public order() {
            this.Url = global::ASE_Project.Properties.Settings.Default.ASE_Project_order_details_order;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event order_enterCompletedEventHandler order_enterCompleted;
        
        /// <remarks/>
        public event address_insertCompletedEventHandler address_insertCompleted;
        
        /// <remarks/>
        public event ven_orderCompletedEventHandler ven_orderCompleted;
        
        /// <remarks/>
        public event usr_orderCompletedEventHandler usr_orderCompleted;
        
        /// <remarks/>
        public event order_detailsCompletedEventHandler order_detailsCompleted;
        
        /// <remarks/>
        public event chart_venCompletedEventHandler chart_venCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/order_enter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int order_enter(string user_id, string ven_id, string details, int total) {
            object[] results = this.Invoke("order_enter", new object[] {
                        user_id,
                        ven_id,
                        details,
                        total});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void order_enterAsync(string user_id, string ven_id, string details, int total) {
            this.order_enterAsync(user_id, ven_id, details, total, null);
        }
        
        /// <remarks/>
        public void order_enterAsync(string user_id, string ven_id, string details, int total, object userState) {
            if ((this.order_enterOperationCompleted == null)) {
                this.order_enterOperationCompleted = new System.Threading.SendOrPostCallback(this.Onorder_enterOperationCompleted);
            }
            this.InvokeAsync("order_enter", new object[] {
                        user_id,
                        ven_id,
                        details,
                        total}, this.order_enterOperationCompleted, userState);
        }
        
        private void Onorder_enterOperationCompleted(object arg) {
            if ((this.order_enterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.order_enterCompleted(this, new order_enterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/address_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int address_insert(string street, string city, string state, string email, string phone, int id, string date1) {
            object[] results = this.Invoke("address_insert", new object[] {
                        street,
                        city,
                        state,
                        email,
                        phone,
                        id,
                        date1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void address_insertAsync(string street, string city, string state, string email, string phone, int id, string date1) {
            this.address_insertAsync(street, city, state, email, phone, id, date1, null);
        }
        
        /// <remarks/>
        public void address_insertAsync(string street, string city, string state, string email, string phone, int id, string date1, object userState) {
            if ((this.address_insertOperationCompleted == null)) {
                this.address_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Onaddress_insertOperationCompleted);
            }
            this.InvokeAsync("address_insert", new object[] {
                        street,
                        city,
                        state,
                        email,
                        phone,
                        id,
                        date1}, this.address_insertOperationCompleted, userState);
        }
        
        private void Onaddress_insertOperationCompleted(object arg) {
            if ((this.address_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.address_insertCompleted(this, new address_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ven_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ven_order(string ven_id) {
            object[] results = this.Invoke("ven_order", new object[] {
                        ven_id});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ven_orderAsync(string ven_id) {
            this.ven_orderAsync(ven_id, null);
        }
        
        /// <remarks/>
        public void ven_orderAsync(string ven_id, object userState) {
            if ((this.ven_orderOperationCompleted == null)) {
                this.ven_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.Onven_orderOperationCompleted);
            }
            this.InvokeAsync("ven_order", new object[] {
                        ven_id}, this.ven_orderOperationCompleted, userState);
        }
        
        private void Onven_orderOperationCompleted(object arg) {
            if ((this.ven_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ven_orderCompleted(this, new ven_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/usr_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] usr_order(string usrid) {
            object[] results = this.Invoke("usr_order", new object[] {
                        usrid});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void usr_orderAsync(string usrid) {
            this.usr_orderAsync(usrid, null);
        }
        
        /// <remarks/>
        public void usr_orderAsync(string usrid, object userState) {
            if ((this.usr_orderOperationCompleted == null)) {
                this.usr_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.Onusr_orderOperationCompleted);
            }
            this.InvokeAsync("usr_order", new object[] {
                        usrid}, this.usr_orderOperationCompleted, userState);
        }
        
        private void Onusr_orderOperationCompleted(object arg) {
            if ((this.usr_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usr_orderCompleted(this, new usr_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/order_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string order_details(int id1) {
            object[] results = this.Invoke("order_details", new object[] {
                        id1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void order_detailsAsync(int id1) {
            this.order_detailsAsync(id1, null);
        }
        
        /// <remarks/>
        public void order_detailsAsync(int id1, object userState) {
            if ((this.order_detailsOperationCompleted == null)) {
                this.order_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onorder_detailsOperationCompleted);
            }
            this.InvokeAsync("order_details", new object[] {
                        id1}, this.order_detailsOperationCompleted, userState);
        }
        
        private void Onorder_detailsOperationCompleted(object arg) {
            if ((this.order_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.order_detailsCompleted(this, new order_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/chart_ven", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int chart_ven(int month, string ven_id) {
            object[] results = this.Invoke("chart_ven", new object[] {
                        month,
                        ven_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void chart_venAsync(int month, string ven_id) {
            this.chart_venAsync(month, ven_id, null);
        }
        
        /// <remarks/>
        public void chart_venAsync(int month, string ven_id, object userState) {
            if ((this.chart_venOperationCompleted == null)) {
                this.chart_venOperationCompleted = new System.Threading.SendOrPostCallback(this.Onchart_venOperationCompleted);
            }
            this.InvokeAsync("chart_ven", new object[] {
                        month,
                        ven_id}, this.chart_venOperationCompleted, userState);
        }
        
        private void Onchart_venOperationCompleted(object arg) {
            if ((this.chart_venCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.chart_venCompleted(this, new chart_venCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void order_enterCompletedEventHandler(object sender, order_enterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class order_enterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal order_enterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void address_insertCompletedEventHandler(object sender, address_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class address_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal address_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ven_orderCompletedEventHandler(object sender, ven_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ven_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ven_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void usr_orderCompletedEventHandler(object sender, usr_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usr_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usr_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void order_detailsCompletedEventHandler(object sender, order_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class order_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal order_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void chart_venCompletedEventHandler(object sender, chart_venCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class chart_venCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal chart_venCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591